const socials = [
  // 'https://event.rakuten.co.jp/disney',
  'https://event.rakuten.co.jp/disney/character/mickeymouse',
  'https://event.rakuten.co.jp/disney/genre/toy',
  'https://event.rakuten.co.jp/marvel',
  'https://event.rakuten.co.jp/marvel/spiderman',
  // 'https://event.rakuten.co.jp/starwars',
  // 'https://event.rakuten.co.jp/starwars/mandalorian',
  'https://event.rakuten.co.jp/coupon',
  'https://event.rakuten.co.jp/anshin',
  'https://event.rakuten.co.jp/anshin/channel',
  'https://event.rakuten.co.jp/anshin/product',
  'https://event.rakuten.co.jp/anshin/rightsmanagement',
  'https://event.rakuten.co.jp/anshin/security',
  'https://event.rakuten.co.jp/anshin/security/caution',
  'https://event.rakuten.co.jp/anshin/shippingdate',
  'https://event.rakuten.co.jp/anshin/voc',
  'https://event.rakuten.co.jp/guide/freeshippingline',
  'https://event.rakuten.co.jp/guide/freeshippingline/opinion',
  'https://event.rakuten.co.jp/guide/shipping',
  'https://event.rakuten.co.jp/guide/shipping/cvs',
  'https://event.rakuten.co.jp/guide/shipping/haco-pos',
  'https://event.rakuten.co.jp/guide/shipping/jp',
  'https://event.rakuten.co.jp/guide/shipping/jp/point-pg',
  // 'https://event.rakuten.co.jp/logistics',
  'https://event.rakuten.co.jp/anshin/anshinshopping',
  'https://event.rakuten.co.jp/anshin/anshinshopping/item',
  'https://event.rakuten.co.jp/anshin/anshinshopping/brand',
  'https://event.rakuten.co.jp/anshin/anshinshopping/en/brand',
  'https://event.rakuten.co.jp/anshin/anshinshopping/en/item',
  'https://event.rakuten.co.jp/anshin/anshinshopping/en/top',
  'https://event.rakuten.co.jp/anshin/anshinshopping/ko/brand',
  'https://event.rakuten.co.jp/anshin/anshinshopping/ko/item',
  'https://event.rakuten.co.jp/anshin/anshinshopping/ko/top',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-cn/brand',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-cn/item',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-cn/top',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-tw/brand',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-tw/item',
  'https://event.rakuten.co.jp/anshin/anshinshopping/zh-tw/top',
]

const supersales = []

const superdeals = [
  'https://event.rakuten.co.jp/superdeal',
  'https://event.rakuten.co.jp/superdeal/special/pointback50',
  'https://event.rakuten.co.jp/superdeal/special/pointback40',
  'https://event.rakuten.co.jp/superdeal/special/pointback30',
  'https://event.rakuten.co.jp/superdeal/special/pointback20',
  'https://event.rakuten.co.jp/superdeal/special/freeshipping',
  'https://event.rakuten.co.jp/superdeal/digitalcode',
  'https://event.rakuten.co.jp/superdeal/timesale',
  'https://event.rakuten.co.jp/superdeal/ranking',
  'https://event.rakuten.co.jp/superdeal/brandlist',
  'https://event.rakuten.co.jp/superdeal/guide',
  'https://event.rakuten.co.jp/superdeal/campaign/mobiledeal/20250321',
  'https://event.rakuten.co.jp/superdeal/special/250321_books',
  'https://event.rakuten.co.jp/superdeal/feature/bigdeal/250321_superdeal',
  'https://event.rakuten.co.jp/superdeal/rba/campaign',
  'https://event.rakuten.co.jp/superdeal/feature/daily/kao',
]

export const pages = {
  superdeals,
  supersales,
  socials,
}
