// Tag List
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=455183376
export const normalTags = [
  'catchcopy_itemname',
  'itemname',
  'catchcopy',
  'itemcaption_caption',
  'itemcaption',
  'caption',
  'item-url',
  'image-url-normal',
  'image-url-large',
  'image-url',
  'starttime',
  'endtime',
  'searchtimestamp',
  'itemnumber',
  'itemprice',
  'kakaku',
  'shopname',
  'shopid',
  'shopurl',
  'reviewnum',
  'reviewave',
  'review_star_avg',
  'asurakuflg',
  'asu_snd_txt',
  'asu_snd_img_s',
  'asu_snd_img_m',
  'asu_snd_area_img_s',
  'asu_snd_area_img_m',
  'asu_closingtime',
  'updatetime',
  'deal-point-rate-calculated',
  'deal-start-date',
  'deal-end-date',
  'image-url-2',
  'image-url-3',
  'image-url-sku',
  'shop_logo_image_1',
  'shop_logo_image_2',
  'shop_logo_image_3',
  'regular_price',
  'tag1',
  //
  'itemname_encoded',
  'itemname_32',
  'itemcaption_32',
]

// Tag List
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=458407304
export const manufactureTags = [
  'disp_ran_cd',
  'product_url',
  'product_cd',
  'product_name',
  'product_no',
  'maker_cd',
  'disp_maker_cd',
  'maker_formal_name',
  'brand_name',
  'open_price_flg',
  'tax_kbn',
  'image_url_normal',
  'image_file_path',
  'item_caption',
  'release_date_disp',
  'sales_Item_num',
  'used_sales_item',
  'prch_Item_num',
  'prch_ave_price',
  'filter_min_price',
  'sales_min_price',
  'used_sales_min_price',
  'used_exclude_sales_min_price',
  'review_num',
  'review_ave',
  'review_star_avg',
  'major_genre_name_path',
  'genre_id',
  'prch_shop_num',
  'ranking_genre_id',
  'ranking_order',
  'pv_ranking_order',
  'updatetime',
  // option
  'item_caption_32',
  'item_caption_encoded',
]

// Tag List
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=458407313
export const couponTags = [
  'couponName',
  'couponCaption',
  'couponCode',
  'itemType',
  'discountType',
  'discountFactor',
  'couponUrlPC',
  'startTime',
  'endTime',
  'rankCondition',
  'itemId',
  'itemName',
  'itemPrice',
  'itemUrlPC',
  'imageUrl',
  'genreId',
  'shopId',
  'shopName',
  'shopImageUrl',
  'shopUrlPC',
  'last_batch_updatetime',
  'min_purchase_price',
  // Option
  'itemname_32',
  'itemname_encoded',
]

// Tag List
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=742721624
export const rankingTags = [
  'genreid',
  'genrename',
  'rank',
  'rankstatus',
  'rankstatus_text',
  'itemname',
  'price',
  'kakaku',
  'itemid',
  'itemurl',
  'imageurl',
  'imageurl64',
  'imageurl128',
  'reviewurl',
  'shopid',
  'shopname',
  'shopurl',
  'genrecolor',
  'updatedate',
  'updatetime',
  'reviewnum',
  'reviewnumcomma',
  'reviewave',
  'reviewaveinteger',
  'reviewavedecimal',
  'review_star_avg',
  'asu_flg_img_s',
  'asu_flg_img_m',
  'mobileurl',
  'last_batch_updatetime',
  // Option
  'itemname_32',
  'itemname_encoded',
]

// TAG LIST
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=1713037547
export const roomTags = ['jsonFileName']

// TAG LIST
// https://confluence.rakuten-it.com/confluence/pages/viewpage.action?pageId=2923568690
export const dealTags = [
  'catchcopy_itemname',
  'itemname',
  'catchcopy',
  'itemcaption',
  'caption',
  'item-url',
  'image-url-normal',
  'image-url-large',
  'image-url',
  'starttime',
  'endtime',
  'searchtimestamp',
  'stock-flg',
  'itemnumber',
  'itemprice',
  'kakaku',
  'shopname',
  'shopid',
  'shopurl',
  'reviewnum',
  'reviewave',
  'review_star_avg',
  'asurakuflg',
  'asu_snd_txt ',
  'asu_snd_img_s',
  'asu_snd_img_m',
  'asu_snd_area_img_s',
  'asu_snd_area_img_m',
  'asu_closingtime',
  'updatetime',
  'deal-point-rate-base',
  'deal-start-date',
  'deal-end-date',
  'image-url-2',
  'image-url-3',
  'image-url-sku',
  'shop_logo_image_1',
  'shop_logo_image_2',
  'shop_logo_image_3',
  'regular_price',
  'tag1',
  // Option
  'itemname_32',
  'itemname_encoded',
  'itemid',
]

export const ALCOR_TYPE = {
  normal: normalTags,
  manufacture: manufactureTags,
  coupon: couponTags,
  ranking: rankingTags,
  room: roomTags,
  deal: dealTags,
}
